### ISSUE TITLE
OSX compilation OPENMP

### ISSUE THREAD

**Issue by fbbfnc** [MaybeShewill-CV/sky-detector#1]
compiling on osx gives this error: 
```
CMake Error at /usr/local/Cellar/cmake/3.13.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.13.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.13.0/share/cmake/Modules/FindOpenMP.cmake:473 (find_package_handle_standard_args)
  CMakeLists.txt:24 (FIND_PACKAGE)
```

Tried this one https://stackoverflow.com/questions/48825416/missing-openmp-c-flags-openmp-c-lib-names but seems not working. 
Any suggestion?
Can you directly provide me the final binary? 
Thank you so much

**Comment by MaybeShewill-CV** [comment]
@fbbfnc I have not tested it on Mac os you may remove all the openmp compile configuration in cmake file and test if it works:)

**Comment by Jason-xin** [comment]
@fbbfnc `brew install llvm`
but I have another question when running "make -j":`ld: symbol(s) not found for architecture x86_64`

**Comment by MaybeShewill-CV** [comment]
@Jason-xin Maybe sth wrong with openmp or pthread:)
