### ISSUE TITLE
No rule to make target '/usr/local/lib/libboost_filesystem.a', needed by 'detector'.  Stop.

### ISSUE THREAD

**Issue by Parker-Lyu** [MaybeShewill-CV/sky-detector#2]
when I run make, I met question like bellow:

Scanning dependencies of target detector
[ 25%] Building CXX object CMakeFiles/detector.dir/main_test.cpp.o
[ 50%] Building CXX object CMakeFiles/detector.dir/sky_detector/imageSkyDetector.cpp.o
[ 75%] Building CXX object CMakeFiles/detector.dir/file_processor/file_system_processor.cpp.o
make[2]: *** No rule to make target '/usr/local/lib/libboost_filesystem.a', needed by 'detector'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/detector.dir/all' failed
make[1]: *** [CMakeFiles/detector.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

how to deal it ?
Thanks

**Comment by MaybeShewill-CV** [comment]
@Parker-Lyu Install boost static lib:)

**Comment by Parker-Lyu** [comment]
When I run "./b2 install" ,  do I need to use param "--prefix=/usr" to specify a install dir, just like described in [https://blog.csdn.net/u011641865/article/details/73498533](url)
Thanks

**Comment by MaybeShewill-CV** [comment]
@Parker-Lyu You may follow the instruction on the Boost website:)

**Comment by Parker-Lyu** [comment]
Thanks, that question solved. 
Another question now:

/usr/bin/x86_64-linux-gnu-ld: attempted static link of dynamic object `/usr/local/lib/libopencv_stitching.so.3.4.2'

Some people say it's because a param "-static", but i don't know where to change it

**Comment by MaybeShewill-CV** [comment]
@Parker-Lyu If you do not have the opencv static lib you may change the project to dynamically compile. You may google how the modify the CMakeList.txt file to statically compile binary file:)

**Comment by Parker-Lyu** [comment]
Thank you for your patience, I got everything OK. 
Good Luck!

**Comment by MaybeShewill-CV** [comment]
@Parker-Lyu Welcome:)

**Comment by r-rajsingh** [comment]
@Parker-Lyu Hey, I am still facing the same issue

**Comment by r-rajsingh** [comment]
do I need to install boost library in the build directory or my root home directory

**Comment by r-rajsingh** [comment]
@Parker-Lyu  /usr/bin/x86_64-linux-gnu-ld: attempted static link of dynamic object `/usr/local/lib/libopencv_stitching.so.3.4.2' 

I am also facing the same issue. Can you please me out?

**Comment by Parker-Lyu** [comment]
My colleague help me solve that problem. Sorry for can't help you

**Comment by r-rajsingh** [comment]
@Parker-Lyu If least possible, please ask your colleague and help me out, because I am stuck over it for the past 3 days. I'd be very thankful to you.

**Comment by Parker-Lyu** [comment]
Accually, I did not use this repo to do my sky-detect work, because it's not perform very good. 
And it's three mouth ago's work, my clleague has forgot the detail.
Sorry about that.
I can give you some suggestion to do sky-detect work. You can  use open source segmentation dataset to make a sky-detect dataset by keep sky pixels value 255 and others 0, such as ADE20k or some other auto drive dataset. Then you can train a segmentation net work to do your sky detect work.
Sorry can't help you more  and good luck

**Comment by weisongwen** [comment]
Solve the issue by re-link the place of  libboost_filesystem.so as follows:

```c++
target_link_libraries(detector
        ${OpenCV_LIBS}
        /usr/lib/x86_64-linux-gnu/libboost_filesystem.so
        /usr/lib/x86_64-linux-gnu/libboost_system.so
        /usr/lib/x86_64-linux-gnu/libglog.so
        )
LINK_DIRECTORIES(/usr/local/lib /usr/lib/x86_64-linux-gnu)

```
