### ISSUE TITLE
I get the following error when I run make -j command

### ISSUE THREAD

**Issue by r-rajsingh** [MaybeShewill-CV/sky-detector#3]
![Screenshot from 2019-07-25 12-33-43](https://user-images.githubusercontent.com/31107560/61853108-b7b87980-aed8-11e9-90d7-32e34d1eea5e.png)

And even after installing this package how do I import this sky-detector package in my Python code and use the function for sky detection? Please help me ASAP. I m stuck on this for past 3 days. I have even installed the boost library.

**Comment by MaybeShewill-CV** [comment]
@r-rajsingh Maybe you need to change from statically compile into dynamicly compile:)

**Comment by r-rajsingh** [comment]
@MaybeShewill-CV  So, where should I make changes in CMakeLists.txt file?

**Comment by r-rajsingh** [comment]
@MaybeShewill-CV  I have changed the     "/usr/local/lib"  to    "/usr/lib/x86_64-linux-gnu"  in CMakeLists.txt because I could not find    "libboost_filesystem.a" , "libboost_system.a" & "libglog.a" in  "/usr/local/lib". So I guess due to this change I made, I am not getting this error.

**Comment by MaybeShewill-CV** [comment]
@r-rajsingh You may google dynamic compile && cmake :)
